name: Running Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Testing
        run: mvn -Dtest=com.napier.sem.AppTest test
      - name: Package and Run docker compose
        run: mvn package -DskipTests
          docker compose up --abort-on-container-exit